language: node_js
node_js:
- stable
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy
- ssh-add .travis/deploy
- echo -e "Host 104.131.168.144\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git remote add dokku dokku@104.131.168.144:bloxparty
- git push dokku
before_install:
- openssl aes-256-cbc -K $encrypted_d786f4b97017_key -iv $encrypted_d786f4b97017_iv
  -in .travis/deploy.enc -out .travis/deploy -d
