language: node_js
node_js:
- stable
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy
- ssh-add .travis/deploy
- echo -e "Host kvnneff.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git remote add dokku dokku@kvnneff.me:bloxparty
- git push dokku master
before_install:
- openssl aes-256-cbc -K $encrypted_c53e712516f8_key -iv $encrypted_c53e712516f8_iv -in .travis/deploy.enc -out .travis/deploy -d
